@if( $interview == 'website')
    @include('fe.interviews.website')
@elseif( $interview == 'address')
    @include('fe.interviews.address')
@elseif( $interview == 'social')
    @include('fe.interviews.social')
@elseif( $interview == 'username')
    @include('fe.interviews.username')
@elseif( $interview == 'aboutyou')
    @include('fe.interviews.about')
@elseif( $interview == 'leadvalue')
    @include('fe.interviews.leadvalue')
@elseif( $interview == 'aboutyouroffer')
    @include('fe.interviews.aboutyouroffer')
@elseif( $interview == 'aboutyourcustomer')
    @include('fe.interviews.aboutyourcustomer')
@elseif ( isset($settings->interview) && $settings->interview == 'pending' )
    @include('fe.interviews.website')
@endif